version: '3.8'

# Note: Podman users can use podman-compose or quadlet for container orchestration
# For Podman: podman-compose up --profile cpu
# For Docker: docker-compose up --profile cpu

services:
  lama-zits-aws-gpu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: lama-zits-pipeline-aws-gpu
    # Note: Podman uses --device nvidia.com/gpu=all instead of runtime: nvidia
    runtime: nvidia # Docker only
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Input/Output directories
      - INPUT_VIDEO_DIR=/data/input_video
      - MASKS_DIR=/data/masks
      - LAMA_OUT_DIR=/data/lama_output
      - ZITS_OUT_DIR=/data/zits_output
      # AWS Configuration
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      # S3 Configuration
      - S3_INPUT_VIDEO=${S3_INPUT_VIDEO:-}
      - S3_OUTPUT_LOCATION=${S3_OUTPUT_LOCATION:-}
      - USE_SYNTHETIC_DATA=${USE_SYNTHETIC_DATA:-true}
    volumes:
      - ./input_video:/data/input_video
      - ./masks:/data/masks
      - ./lama_output:/data/lama_output
      - ./zits_output:/data/zits_output
      - ./aws_output:/data/aws_output
    profiles:
      - aws-gpu

  lama-zits-aws-cpu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: lama-zits-pipeline-aws-cpu
    environment:
      # Input/Output directories
      - INPUT_VIDEO_DIR=/data/input_video
      - MASKS_DIR=/data/masks
      - LAMA_OUT_DIR=/data/lama_output
      - ZITS_OUT_DIR=/data/zits_output
      # AWS Configuration
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      # S3 Configuration
      - S3_INPUT_VIDEO=${S3_INPUT_VIDEO:-}
      - S3_OUTPUT_LOCATION=${S3_OUTPUT_LOCATION:-}
      - USE_SYNTHETIC_DATA=${USE_SYNTHETIC_DATA:-true}
    volumes:
      - ./input_video:/data/input_video
      - ./masks:/data/masks
      - ./lama_output:/data/lama_output
      - ./zits_output:/data/zits_output
      - ./aws_output:/data/aws_output
    profiles:
      - aws-cpu

  # Original profiles for backward compatibility
  lama-zits-gpu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: lama-zits-pipeline-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - INPUT_VIDEO_DIR=/data/input_video
      - MASKS_DIR=/data/masks
      - LAMA_OUT_DIR=/data/lama_output
      - ZITS_OUT_DIR=/data/zits_output
      - USE_SYNTHETIC_DATA=true
    volumes:
      - ./input_video:/data/input_video
      - ./masks:/data/masks
      - ./lama_output:/data/lama_output
      - ./zits_output:/data/zits_output
    profiles:
      - gpu

  lama-zits-cpu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: lama-zits-pipeline-cpu
    environment:
      - INPUT_VIDEO_DIR=/data/input_video
      - MASKS_DIR=/data/masks
      - LAMA_OUT_DIR=/data/lama_output
      - ZITS_OUT_DIR=/data/zits_output
      - USE_SYNTHETIC_DATA=true
    volumes:
      - ./input_video:/data/input_video
      - ./masks:/data/masks
      - ./lama_output:/data/lama_output
      - ./zits_output:/data/zits_output
    profiles:
      - cpu
